DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='Projects';
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR', 'Projects', 'Chantier/Affaire');

DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='SearchIntoProjects';
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR', 'SearchIntoProjects', 'Chantiers/Affaires');

DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='RefProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectRef';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectId';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectLabel';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsArea';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectStatus';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='PrivateProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsImContactFor';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='AllAllowedProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='AllProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='MyProjectsDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsPublicDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='TasksOnProjectsPublicDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsPublicTaskDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='TasksOnProjectsDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='MyTasksDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='OnlyOpenedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ClosedProjectsAreHidden';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='TasksPublicDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='TasksDesc';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='AllTaskVisibleButEditIfYouAreAssigned';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='OnlyYourTaskAreVisible';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ImportDatasetTasks';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectCategories';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='NewProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='AddProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='DeleteAProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ConfirmDeleteAProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='OpenedProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='OpportunitiesStatusForOpenedProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='OpportunitiesStatusForProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ShowProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='SetProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='NoProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='NbOfProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='TasksOnOpenedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='MyProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='MyProjectsArea';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListProposalsAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListOrdersAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListInvoicesAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListPredefinedInvoicesAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListSupplierOrdersAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListSupplierInvoicesAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListContractAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListShippingAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListFichinterAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListExpenseReportsAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListDonationsAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListVariousPaymentsAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListActionsAssociatedProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ListTaskTimeUserProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ActivityOnProjectToday';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ActivityOnProjectYesterday';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ActivityOnProjectThisWeek';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ActivityOnProjectThisMonth';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ActivityOnProjectThisYear';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ChildOfProjectTask';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='NotOwnerOfProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='CantRemoveProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ValidateProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ConfirmValidateProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='CloseAProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ConfirmCloseAProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='AlsoCloseAProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ReOpenAProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ConfirmReOpenAProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectContact';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ActionsOnProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='YouAreNotContactOfProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='UserIsNotContactOfProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsDedicatedToThisThirdParty';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='NoTasks';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ThisWillAlsoRemoveTasks';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='IfNeedToUseOhterObjectKeepEmpty';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='CloneProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='CloneProjectFiles';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='CloneMoveDate';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ConfirmCloneProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsAndTasksLines';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectCreatedInDolibarr';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectModifiedInDolibarr';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='TypeContact_project_internal_PROJECTLEADER';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='TypeContact_project_external_PROJECTLEADER';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='DocumentModelBeluga';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='DocumentModelBaleine';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectMustBeValidatedFirst';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsWithThisUserAsContact';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ResourceNotAssignedToProject';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ManageTasks';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ManageOpportunitiesStatus';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectNbProjectByMonth';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='ProjectsStatistics';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='TasksStatistics';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='OpenedProjectsByThirdparties';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='LatestProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='LatestModifiedProjects';
DELETE FROM llx_overwrite_trans WHERE lang='fr_FR' AND transkey='AllowCommentOnProject';

INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','RefProject','Réf. chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectRef','Ref chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectId','Id chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectLabel','Libellé chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsArea','Espace chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectStatus','Statut chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','PrivateProject','Contacts chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsImContactFor','Chantiers dont je suis un contact explicite');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','AllAllowedProjects','Tout chantier que je peux lire (les miens + public)');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','AllProjects','Tous les chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','MyProjectsDesc','Cette vue est limitée aux chantiers dont vous êtres contact');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsPublicDesc','Cette vue présente tous les chantiers pour lesquels vous êtes habilité à avoir une visibilité.');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','TasksOnProjectsPublicDesc','Cette vue affiche toutes les tâches de chantiers selon vos permissions utilisateur');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsPublicTaskDesc','Cette vue présente tous les chantiers et tâches pour lesquels vous êtes habilité à avoir une visibilité.');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsDesc','Cette vue présente tous les chantiers (vos habilitations vous offrant une vue exhaustive).');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','TasksOnProjectsDesc','Cette vue présente toutes les tâches sur tous les chantiers (vos permissions d\'utilisateur vous accordent la permission de voir tout).');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','MyTasksDesc','Cette vue est limitée au chantiers ou tâches dont vous êtes contact');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','OnlyOpenedProject','Seuls les chantiers ouverts sont visibles (les chantiers à l\'état brouillon ou fermé ne sont pas visibles).');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ClosedProjectsAreHidden','Les chantiers fermés ne sont pas visible.');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','TasksPublicDesc','Cette vue présente tous les chantiers et tâches pour lesquels vous êtes habilité à avoir une visibilité.');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','TasksDesc','Cette vue présente tous les chantiers et tâches (vos habilitations vous offrant une vue exhaustive).');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','AllTaskVisibleButEditIfYouAreAssigned','Toutes les tâches des chantiers sont visibles mais il n\'est possible de saisir du temps passé que sur celles assignées à l\'utilisateur sélectionné.\nAssignez la tâche si elle ne l\'est pas déjà pour pouvoir saisir du temps dessus.');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','OnlyYourTaskAreVisible','Seules les tâches qui vous sont assignées sont visibles. Assignez vous une tâche pour la voir et saisir du temps passé');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ImportDatasetTasks','Tâches des chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectCategories','Catégories/tags de chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','NewProject','Nouveau chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','AddProject','Créer chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','DeleteAProject','Supprimer un chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ConfirmDeleteAProject','Êtes-vous sûr de vouloir supprimer ce chantier ?');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','OpenedProjects','Chantiers ouverts');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','OpportunitiesStatusForOpenedProjects','Montant des opportunités des chantiers ouverts par statut');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','OpportunitiesStatusForProjects','Montant des opportunités des chantiers par statut');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ShowProject','Afficher chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','SetProject','Définir chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','NoProject','Aucun chantier défini ou responsable');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','NbOfProjects','Nombre de chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','TasksOnOpenedProject','Tâches sur les chantiers ouverts');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','MyProjects','Mes chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','MyProjectsArea','Espace Mes chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListProposalsAssociatedProject','Liste des propositions commerciales associées au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListOrdersAssociatedProject','Liste des commandes clients associées au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListInvoicesAssociatedProject','Liste des factures clients associées au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListPredefinedInvoicesAssociatedProject','Liste des modèles de facture client associées au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListSupplierOrdersAssociatedProject','Liste des commandes fournisseurs associées au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListSupplierInvoicesAssociatedProject','Liste des factures fournisseurs associées au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListContractAssociatedProject','Liste des contrats associés au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListShippingAssociatedProject','Liste des expéditions associées avec le chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListFichinterAssociatedProject','Liste des interventions associées au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListExpenseReportsAssociatedProject','Liste des notes de frais associées avec ce chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListDonationsAssociatedProject','Liste des dons associés au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListVariousPaymentsAssociatedProject','Liste des frais divers liés au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListActionsAssociatedProject','Liste des événements associés au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ListTaskTimeUserProject','Liste du temps consommé sur les tâches d\'un chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ActivityOnProjectToday','Activité chantier aujourd\'hui');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ActivityOnProjectYesterday','Activité chantier hier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ActivityOnProjectThisWeek','Activité sur les chantiers cette semaine');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ActivityOnProjectThisMonth','Activité sur les chantiers ce mois');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ActivityOnProjectThisYear','Activité sur les chantiers cette année');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ChildOfProjectTask','Fille du chantier/tâche');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','NotOwnerOfProject','Non responsable de ce chantier privé');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','CantRemoveProject','Ce chantier ne peut être supprimé car il est référencé par de nombreux objets (factures, commandes ou autre). voir la liste sur l\'onglet Reférents.');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ValidateProject','Valider chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ConfirmValidateProject','Êtes-vous sûr de vouloir valider ce chantier ?');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','CloseAProject','Clore chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ConfirmCloseAProject','Êtes-vous sûr de vouloir clore ce chantier ?');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','AlsoCloseAProject','Fermer également le chantier (laissez-le ouvert si vous devez suivre la production de tâches dessus)');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ReOpenAProject','Réouvrir chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ConfirmReOpenAProject','Êtes-vous sûr de vouloir rouvrir ce chantier ?');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectContact','Contacts chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ActionsOnProject','Événements sur le chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','YouAreNotContactOfProject','Vous n\'êtes pas contact de ce chantier privé');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','UserIsNotContactOfProject','L\'utilisateur n\'est pas un contact/adresse de ce chantier privé');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsDedicatedToThisThirdParty','Chantiers dédiés à ce tiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','NoTasks','Aucune tâche pour ce chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ThisWillAlsoRemoveTasks','Cette opération détruira également les tâches du chantier (<b>%s</b> tâches actuellement) et le suivi des consommés.');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','IfNeedToUseOhterObjectKeepEmpty','Si des objets (facture, commande, ...), appartenant à un autre tiers que celui choisi, doivent être liés au chantier à créer, laisser vide afin de laisser le chantier multi-tiers.');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','CloneProject','Cloner le chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','CloneProjectFiles','Cloner les pièces jointes du chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','CloneMoveDate','Mettre à jour les dates chantier/tâches à partir de maintenant');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ConfirmCloneProject','Êtes-vous sûr de vouloir cloner ce chantier ?');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsAndTasksLines','Chantiers et tâches');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectCreatedInDolibarr','Chantier %s créé');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectModifiedInDolibarr','Chantier %s modifié');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','TypeContact_project_internal_PROJECTLEADER','Chef de chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','TypeContact_project_external_PROJECTLEADER','Chef de chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','DocumentModelBeluga','Modèle de document de rapport pour l\'aperçu chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','DocumentModelBaleine','Modèles de document de rapport de tâches de chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectMustBeValidatedFirst','Le chantier doit être validé d\'abord');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsWithThisUserAsContact','Chantiers avec cet utilisateur comme contact');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ResourceNotAssignedToProject','Non assigné au chantier');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ManageTasks','Utiliser les chantiers pour suivre les tâches');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ManageOpportunitiesStatus','Utiliser les chantiers pour suivre les affaires / opportunités');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectNbProjectByMonth','Nb de chantiers créés par mois');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','ProjectsStatistics','Statistics sur les chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','TasksStatistics','Statistiques sur le chantier/tâche principale');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','OpenedProjectsByThirdparties','Chantiers ouverts par tiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','LatestProjects','Les %s derniers chantiers');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','LatestModifiedProjects','Les %s derniers chantiers modifiés');
INSERT INTO llx_overwrite_trans (entity, lang, transkey, transvalue) VALUES (1, 'fr_FR','AllowCommentOnProject','Autoriser les commentaires utilisateur sur les chantiers');
